# Generated by Django 5.0.6 on 2024-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("product_name", models.CharField(max_length=100)),
                ("category", models.CharField(default="", max_length=50)),
                ("discounted_price", models.IntegerField(default=0)),
                ("actual_price", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0, max_length=5)),
                ("about_product", models.CharField(default="", max_length=250)),
            ],
        ),
    ]
