# Generated by Django 5.0.6 on 2024-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="image",
            field=models.ImageField(default="", upload_to="shops/images"),
        ),
    ]
