# Generated by Django 5.0.6 on 2024-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_productdetails_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_name",
            field=models.CharField(max_length=200),
        ),
    ]
