# Generated by Django 5.0.6 on 2024-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_productdetails_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
