# Generated by Django 5.0.6 on 2024-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="display_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
