# Generated by Django 5.0.6 on 2024-08-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_productdetails_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=90),
        ),
    ]
