# Generated by Django 5.0.6 on 2024-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_customuser_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_id",
            field=models.AutoField(
                default=1, max_length=10, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
