# Generated by Django 5.0.6 on 2024-08-31 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_customuser_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("1a90880a-f826-4559-b1cd-dcb01d547751"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
