# Generated by Django 5.0.6 on 2024-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_remove_customuser_id_customuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
