# Generated by Django 5.1 on 2024-08-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
