# Generated by Django 5.0.6 on 2024-08-31 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_remove_customuser_id_customuser_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default=uuid.UUID("e82edb53-57be-4eb1-aae8-cd58a05cd57f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
