# Generated by Django 5.1 on 2024-08-31 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_remove_customuser_user_id_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=uuid.UUID('ffe3affd-4405-4032-bf83-2765cf061c41'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
