# Generated by Django 5.1 on 2024-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_remove_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
