# Generated by Django 5.0.6 on 2024-08-31 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0010_alter_customuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
