# Generated by Django 5.1 on 2024-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_remove_customuser_id_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
