# Generated by Django 5.0.6 on 2024-08-31 09:42

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0011_alter_customuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
