# Generated by Django 5.0.6 on 2024-09-03 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0011_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default=uuid.UUID("f40194d6-ea52-4d35-afab-6e90316df96f"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="image",
            field=models.ImageField(upload_to="shops/images"),
        ),
    ]
