# Generated by Django 5.0.6 on 2024-08-31 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_alter_customuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("4ebb86ad-d47b-4669-9c77-97a6a5301c1d"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
