# Generated by Django 5.1 on 2024-08-31 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_customuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=uuid.UUID('6e6506f2-dad8-4554-88a8-1590215fd1e5'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
