# Generated by Django 5.1 on 2024-08-31 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_remove_customuser_user_id_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=uuid.UUID('f7c7d2be-4b7e-4ab9-8c1c-d9084436a8d6'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
